logging:
  level:
    root: INFO
    com.aot.fantomeapp: DEBUG
    sql: DEBUG
    sql_params: TRACE

spring:
  docker:
    compose:
      enabled: false
      file: docker-compose.yaml
  config:
    import: optional:file:.env[.properties]
  devtools:
    livereload:
      enabled: false
