CREATE TABLE foo
(
   id bigserial primary key,
   name varchar(255),
   attribut_camel_case varchar(255)
);

CREATE TABLE bar
(
   id     bigserial primary key,
   foo_id bigint references foo(id),
   name   varchar(255)
);

INSERT INTO foo (name, attribut_camel_case)
VALUES
   ('Foo 1', 'lorem'),
   ('Foo 2', 'lorem'),
   ('Foo 3', 'lorem'),
   ('Foo 4', 'lorem'),
   ('Foo 5', 'lorem'),
   ('Foo 6', 'lorem'),
   ('Foo 7', 'lorem'),
   ('Foo 8', 'lorem'),
   ('Foo 9', 'lorem'),
   ('Foo 10', 'lorem'),
   ('Foo 11', 'lorem'),
   ('Foo 12', 'lorem'),
   ('Foo 13', 'lorem'),
   ('Foo 14', 'lorem'),
   ('Foo 15', 'lorem'),
   ('Foo 16', 'lorem'),
   ('Foo 17',  'lorem'),
   ('Foo 18',  'lorem'),
   ('Foo 19',  'lorem'),
   ('Foo 20',  'lorem'),
   ('Foo 21',  'lorem'),
   ('Foo 22',  'lorem'),
   ('Foo 23',  'lorem'),
   ('Foo 24',  'lorem'),
   ('Foo 25',  'lorem'),
   ('Foo 26',  'lorem'),
   ('Foo 27',  'lorem'),
   ('Foo 28',  'lorem'),
   ('Foo 29',   'lorem'),
   ('Foo 30',  'lorem'),
   ('Foo 31',  'lorem'),
   ('Foo 32',  'lorem'),
   ('Foo 33',  'lorem'),
   ('Foo 34',  'lorem'),
   ('Foo 35',  'lorem'),
   ('Foo 36',  'lorem'),
   ('Foo 37',  'lorem'),
   ('Foo 38',  'lorem'),
   ('Foo 39',   'lorem'),
   ('Foo 40',  'lorem'),
   ('Foo 41',  'lorem'),
   ('Foo 42',  'lorem'),
   ('Foo 43',  'lorem'),
   ('Foo 44',  'lorem'),
   ('Foo 45',  'lorem'),
   ('Foo 46',  'lorem'),
   ('Foo 47',  'lorem'),
   ('Foo 48',  'lorem'),
   ('Foo 49',   'lorem'),
   ('Foo 50',  'lorem'),
   ('Foo 51',  'lorem'),
   ('Foo 52',  'lorem'),
   ('Foo 53',  'lorem'),
   ('Foo 54',  'lorem'),
   ('Foo 55',  'lorem'),
   ('Foo 56',  'lorem'),
   ('Foo 57',  'lorem'),
   ('Foo 58',  'lorem'),
   ('Foo 59',   'lorem'),
   ('Foo 60',  'lorem'),
   ('Foo 61',  'lorem'),
   ('Foo 62',  'lorem'),
   ('Foo 63',  'lorem'),
   ('Foo 64',  'lorem'),
   ('Foo 65',  'lorem'),
   ('Foo 66',  'lorem'),
   ('Foo 67',  'lorem'),
   ('Foo 68',  'lorem'),
   ('Foo 69',   'lorem'),
   ('Foo 70',  'lorem'),
   ('Foo 71',  'lorem'),
   ('Foo 72',  'lorem'),
   ('Foo 73',  'lorem'),
   ('Foo 74',  'lorem'),
   ('Foo 75',  'lorem'),
   ('Foo 76',  'lorem'),
   ('Foo 77',  'lorem'),
   ('Foo 78',  'lorem'),
   ('Foo 79',   'lorem'),
   ('Foo 80',  'lorem'),
   ('Foo 81',  'lorem'),
   ('Foo 82',  'lorem'),
   ('Foo 83',  'lorem'),
   ('Foo 84',  'lorem'),
   ('Foo 85',  'lorem'),
   ('Foo 86',  'lorem'),
   ('Foo 87',  'lorem'),
   ('Foo 88',  'lorem'),
   ('Foo 89',   'lorem'),
   ('Foo 90',  'lorem'),
   ('Foo 91',  'lorem'),
   ('Foo 92',  'lorem'),
   ('Foo 93',  'lorem'),
   ('Foo 94',  'lorem'),
   ('Foo 95',  'lorem'),
   ('Foo 96',  'lorem'),
   ('Foo 97',  'lorem'),
   ('Foo 98',  'lorem'),
   ('Foo 99',   'lorem'),
   ('Foo 100',   'lorem');

-- Ajout de "bars" sur les "foos" avec une répartition aléatoire
INSERT INTO bar (foo_id, name)
VALUES
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq))),
   ((SELECT f.id FROM foo f WHERE f.id = (SELECT round(RANDOM() * last_value) FROM foo_id_seq)), concat('Bar', (SELECT last_value FROM bar_id_seq)));
